#port
server:
  port: 80
#database
spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:XE
    username: root
    password: root
    driver-class-name: oracle.jdbc.driver.OracleDriver
  thymeleaf:
    cache: false
    prefix: classpath:templates/
    suffix: .html
    encoding: UTF-8
    mode: HTML
#mybatis
mybatis:
  config: confing.xml
  type-aliases-package: com.sist.web.vo
  mapper-locations: mybatis/mapper/*.xml
#jpa
#spring.jpa.database=mysql
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
#spring.jpa.properties.hibernate.dialect.storage_engine=innodb
#logging.level.org.hibernate=info
#spring.jpa.properties.hibernate.show_sql=true
#spring.jpa.properties.hibernate.format_sql=true
#spring.jpa.properties.hibernate.user_sql_comments=true
#thymeleaf

